package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
)

type manifest struct {
	SchemaVersion string `json:"schema_version"`
	ToolCatalog   struct {
		SchemaVersion string `json:"schema_version"`
	} `json:"tool_catalog"`
	Execution struct {
		ProtocolVersion string `json:"protocol_version"`
	} `json:"execution"`
	Features struct {
		Approval          string `json:"approval"`
		DomainEpoch       string `json:"domain_epoch"`
		ExecutionProtocol string `json:"execution_protocol"`
		OperationLedger   string `json:"operation_ledger"`
		TaskBridge        string `json:"task_bridge"`
		ToolCatalog       string `json:"tool_catalog"`
	} `json:"features"`
	AssetConfigLock struct {
		Version      int   `json:"version"`
		StaleAfterMS int64 `json:"stale_after_ms"`
	} `json:"asset_config_lock"`
}

func main() {
	check := flag.Bool("check", false, "report generated contract drift without writing")
	root := flag.String("root", ".", "repository root")
	flag.Parse()
	if flag.NArg() != 0 {
		fmt.Fprintln(os.Stderr, "generate-runtime-contracts accepts only --check and --root")
		os.Exit(2)
	}
	if err := run(*root, *check); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(root string, check bool) error {
	root, err := filepath.Abs(root)
	if err != nil {
		return fmt.Errorf("resolve repository root: %w", err)
	}
	raw, err := os.ReadFile(filepath.Join(root, "contracts", "runtime-contracts.json"))
	if err != nil {
		return fmt.Errorf("read runtime contract manifest: %w", err)
	}
	contract, err := parseManifest(raw)
	if err != nil {
		return err
	}
	outputs, err := generate(contract)
	if err != nil {
		return err
	}
	var drift []string
	for relative, content := range outputs {
		path := filepath.Join(root, filepath.FromSlash(relative))
		if check {
			current, readErr := os.ReadFile(path)
			if readErr != nil && !errors.Is(readErr, os.ErrNotExist) {
				return fmt.Errorf("read generated contract %s: %w", relative, readErr)
			}
			if readErr != nil || !bytes.Equal(normalizeLF(current), content) {
				drift = append(drift, relative)
			}
			continue
		}
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return fmt.Errorf("create generated contract directory: %w", err)
		}
		if err := os.WriteFile(path, content, 0o644); err != nil {
			return fmt.Errorf("write generated contract %s: %w", relative, err)
		}
	}
	if len(drift) != 0 {
		return fmt.Errorf("generated runtime contracts differ from manifest: %s", strings.Join(drift, ", "))
	}
	return nil
}

func parseManifest(raw []byte) (manifest, error) {
	var value manifest
	decoder := json.NewDecoder(bytes.NewReader(raw))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&value); err != nil {
		return value, fmt.Errorf("decode runtime contract manifest: %w", err)
	}
	if value.SchemaVersion != "hera.runtime-contracts/1" {
		return value, fmt.Errorf("unsupported runtime contract manifest %q", value.SchemaVersion)
	}
	stringsRequired := map[string]string{
		"tool_catalog.schema_version": value.ToolCatalog.SchemaVersion,
		"execution.protocol_version":  value.Execution.ProtocolVersion,
		"features.approval":           value.Features.Approval,
		"features.domain_epoch":       value.Features.DomainEpoch,
		"features.execution_protocol": value.Features.ExecutionProtocol,
		"features.operation_ledger":   value.Features.OperationLedger,
		"features.task_bridge":        value.Features.TaskBridge,
		"features.tool_catalog":       value.Features.ToolCatalog,
	}
	for name, field := range stringsRequired {
		if strings.TrimSpace(field) == "" {
			return value, fmt.Errorf("runtime contract field %s is required", name)
		}
	}
	if value.AssetConfigLock.Version < 1 || value.AssetConfigLock.StaleAfterMS < 1 {
		return value, fmt.Errorf("asset_config_lock version and stale_after_ms must be positive")
	}
	return value, nil
}

func generate(value manifest) (map[string][]byte, error) {
	goSource := fmt.Sprintf(`// Code generated by tools/generate-runtime-contracts; DO NOT EDIT.

package protocol

const (
	RuntimeContractsSchemaVersion = %q
	ToolCatalogSchemaVersion      = %q
	ExecutionProtocolVersion      = %q

	FeatureApprovalV1          = %q
	FeatureDomainEpochV1       = %q
	FeatureExecutionProtocolV1 = %q
	FeatureOperationLedgerV1   = %q
	FeatureTaskBridgeV1        = %q
	FeatureToolCatalogV1       = %q

	AssetConfigLockVersion                = %d
	AssetConfigLockStaleAfterMilliseconds = int64(%d)
)
`, value.SchemaVersion, value.ToolCatalog.SchemaVersion, value.Execution.ProtocolVersion,
		value.Features.Approval, value.Features.DomainEpoch, value.Features.ExecutionProtocol,
		value.Features.OperationLedger, value.Features.TaskBridge, value.Features.ToolCatalog,
		value.AssetConfigLock.Version, value.AssetConfigLock.StaleAfterMS)
	formatted, err := format.Source([]byte(goSource))
	if err != nil {
		return nil, fmt.Errorf("format generated Go contract: %w", err)
	}
	csSource := fmt.Sprintf(`// Code generated by tools/generate-runtime-contracts; DO NOT EDIT.

namespace HeraAgent
{
    internal static class ProtocolContracts
    {
        internal const string RuntimeContractsSchemaVersion = %s;
        internal const string ToolCatalogSchemaVersion = %s;
        internal const string ExecutionProtocolVersion = %s;

        internal const string FeatureApprovalV1 = %s;
        internal const string FeatureDomainEpochV1 = %s;
        internal const string FeatureExecutionProtocolV1 = %s;
        internal const string FeatureOperationLedgerV1 = %s;
        internal const string FeatureTaskBridgeV1 = %s;
        internal const string FeatureToolCatalogV1 = %s;

        internal const int AssetConfigLockVersion = %d;
        internal const long AssetConfigLockStaleAfterMilliseconds = %dL;
    }
}
`, csString(value.SchemaVersion), csString(value.ToolCatalog.SchemaVersion), csString(value.Execution.ProtocolVersion),
		csString(value.Features.Approval), csString(value.Features.DomainEpoch), csString(value.Features.ExecutionProtocol),
		csString(value.Features.OperationLedger), csString(value.Features.TaskBridge), csString(value.Features.ToolCatalog),
		value.AssetConfigLock.Version, value.AssetConfigLock.StaleAfterMS)
	return map[string][]byte{
		"internal/protocol/contracts_gen.go":                        normalizeLF(formatted),
		"AgentConnector/Editor/Core/ProtocolContracts.Generated.cs": normalizeLF([]byte(csSource)),
	}, nil
}

func csString(value string) string {
	encoded, _ := json.Marshal(value)
	return string(encoded)
}

func normalizeLF(content []byte) []byte {
	return bytes.ReplaceAll(bytes.ReplaceAll(content, []byte("\r\n"), []byte("\n")), []byte("\r"), []byte("\n"))
}
