package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"unicode/utf8"
)

const developmentHeading = "## 7. Developing hera-agent-unity itself (co-development)"

const cursorFrontmatter = `---
description: Use hera-agent-unity CLI for any Unity Editor task — measure, do not guess, save tokens
globs: **/*.cs,**/*.unity,**/*.prefab,**/*.asmdef,**/*.mat,**/*.asset,**/Assets/**
alwaysApply: true
---

`

const skillFrontmatter = `---
name: hera-agent-unity
description: Control the running Unity Editor via the hera-agent-unity CLI — execute C#, read the console, drive Play Mode, run tests, inspect live types
---

`

func main() {
	check := flag.Bool("check", false, "report generated agent-guide drift without writing")
	flag.Parse()
	if flag.NArg() != 0 {
		fmt.Fprintln(os.Stderr, "sync-agent-guides accepts only --check")
		os.Exit(2)
	}
	root, err := os.Getwd()
	if err != nil {
		fmt.Fprintf(os.Stderr, "resolve repository root: %v\n", err)
		os.Exit(1)
	}
	if err := syncGuides(root, *check); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func syncGuides(root string, check bool) error {
	source, err := os.ReadFile(filepath.Join(root, "AGENTS.md"))
	if err != nil {
		return fmt.Errorf("read canonical AGENTS.md: %w", err)
	}
	guides, err := generateGuides(source)
	if err != nil {
		return err
	}

	paths := make([]string, 0, len(guides))
	for path := range guides {
		paths = append(paths, path)
	}
	slices.Sort(paths)

	var drift []string
	for _, path := range paths {
		target := filepath.Join(root, filepath.FromSlash(path))
		if check {
			current, readErr := os.ReadFile(target)
			if readErr != nil && !errors.Is(readErr, os.ErrNotExist) {
				return fmt.Errorf("read generated guide %s: %w", path, readErr)
			}
			if readErr != nil || !bytes.Equal(current, guides[path]) {
				drift = append(drift, path)
			}
			continue
		}
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			return fmt.Errorf("create guide directory for %s: %w", path, err)
		}
		if err := os.WriteFile(target, guides[path], 0o644); err != nil {
			return fmt.Errorf("write generated guide %s: %w", path, err)
		}
	}
	if len(drift) != 0 {
		return fmt.Errorf("generated agent guides differ from AGENTS.md: %s", strings.Join(drift, ", "))
	}
	return nil
}

func generateGuides(rawSource []byte) (map[string][]byte, error) {
	if !utf8.Valid(rawSource) {
		return nil, errors.New("canonical AGENTS.md is not valid UTF-8")
	}
	source := normalizeLF(rawSource)
	marker := "\n" + developmentHeading + "\n"
	index := strings.Index(source, marker)
	if index < 0 {
		return nil, fmt.Errorf("canonical AGENTS.md is missing %q", developmentHeading)
	}
	distributable := strings.TrimRight(source[:index], "\n") + "\n"

	return map[string][]byte{
		"AGENT.md":                                 []byte(distributable),
		"cmd/AGENT.md":                             []byte(distributable),
		".cursor/rules/hera-agent-unity.mdc":       []byte(cursorFrontmatter + distributable),
		".github/copilot-instructions.md":          []byte(copilotStub),
		"GEMINI.md":                                []byte(geminiStub),
		".agents/agents.md":                        []byte(workspaceAgentsStub),
		".agents/skills/hera-agent-unity/SKILL.md": []byte(skillFrontmatter + distributable),
	}, nil
}

func normalizeLF(content []byte) string {
	normalized := strings.ReplaceAll(string(content), "\r\n", "\n")
	return strings.ReplaceAll(normalized, "\r", "\n")
}

const copilotStub = `# GitHub Copilot Instructions

Use [` + "`AGENTS.md`" + `](../AGENTS.md) as the canonical cross-tool project rules.
This file is generated by ` + "`go run ./tools/sync-agent-guides`" + ` and must not be edited independently.
`

const geminiStub = `# hera-agent-unity — Project Rule (AntiGravity)

Use [` + "`AGENTS.md`" + `](AGENTS.md) as the canonical cross-tool project rules.
The generated on-demand skill is [` + "`.agents/skills/hera-agent-unity/SKILL.md`" + `](.agents/skills/hera-agent-unity/SKILL.md).
This file is generated by ` + "`go run ./tools/sync-agent-guides`" + ` and must not be edited independently.
`

const workspaceAgentsStub = `# AntiGravity Workspace Agents

Use [` + "`AGENTS.md`" + `](../AGENTS.md) as the canonical cross-tool project rules and [` + "`GEMINI.md`" + `](../GEMINI.md) as the AntiGravity entry.
Invoke the generated [` + "`hera-agent-unity`" + ` skill](skills/hera-agent-unity/SKILL.md) for Unity Editor work.
This file is generated by ` + "`go run ./tools/sync-agent-guides`" + ` and must not be edited independently.
`
