using System;
using System.Collections.Generic;

namespace HeraAgent.Tests
{
    internal static class ToolSafetyExpectations
    {
        internal static readonly IReadOnlyDictionary<string, HeraRiskClass> ExpectedRisk
            = new Dictionary<string, HeraRiskClass>(StringComparer.Ordinal)
            {
                ["console"] = HeraRiskClass.ReadOnly,
                ["describe_shader"] = HeraRiskClass.ReadOnly,
                ["describe_type"] = HeraRiskClass.ReadOnly,
                ["detect_assets"] = HeraRiskClass.Write,
                ["exec"] = HeraRiskClass.ArbitraryCode,
                ["find_gameobjects"] = HeraRiskClass.ReadOnly,
                ["find_method"] = HeraRiskClass.ReadOnly,
                ["game_feel"] = HeraRiskClass.ReadOnly,
                ["input"] = HeraRiskClass.Write,
                ["list_assemblies"] = HeraRiskClass.ReadOnly,
                ["log"] = HeraRiskClass.Write,
                ["manage_animation"] = HeraRiskClass.Write,
                ["manage_asset_import"] = HeraRiskClass.Write,
                ["manage_assets"] = HeraRiskClass.Destructive,
                ["manage_components"] = HeraRiskClass.Destructive,
                ["manage_editor"] = HeraRiskClass.Destructive,
                ["manage_gameobject"] = HeraRiskClass.Destructive,
                ["manage_material"] = HeraRiskClass.Write,
                ["manage_packages"] = HeraRiskClass.PackageChange,
                ["manage_prefab"] = HeraRiskClass.Destructive,
                ["manage_ui"] = HeraRiskClass.Write,
                ["menu"] = HeraRiskClass.ArbitraryCode,
                ["profiler"] = HeraRiskClass.Destructive,
                ["refresh_unity"] = HeraRiskClass.Write,
                ["reserialize"] = HeraRiskClass.Write,
                ["run_tests"] = HeraRiskClass.Write,
                ["scene"] = HeraRiskClass.Destructive,
                ["screenshot"] = HeraRiskClass.Write,
                ["ui_slop"] = HeraRiskClass.ReadOnly,
                ["unity_docs"] = HeraRiskClass.ReadOnly,
                ["input/inspect"] = HeraRiskClass.ReadOnly,
                ["input/state"] = HeraRiskClass.ReadOnly,
                ["manage_asset_import/get"] = HeraRiskClass.ReadOnly,
                ["manage_assets/find"] = HeraRiskClass.ReadOnly,
                ["manage_components/get"] = HeraRiskClass.ReadOnly,
                ["manage_components/list"] = HeraRiskClass.ReadOnly,
                ["manage_editor/get_selection"] = HeraRiskClass.ReadOnly,
                ["manage_gameobject/get_transform"] = HeraRiskClass.ReadOnly,
                ["manage_material/get"] = HeraRiskClass.ReadOnly,
                ["manage_packages/list"] = HeraRiskClass.ReadOnly,
                ["manage_ui/get_rect"] = HeraRiskClass.ReadOnly,
                ["menu/list"] = HeraRiskClass.ReadOnly,
                ["profiler/hierarchy"] = HeraRiskClass.ReadOnly,
                ["profiler/status"] = HeraRiskClass.ReadOnly,
                ["scene/info"] = HeraRiskClass.ReadOnly,
                ["scene/list"] = HeraRiskClass.ReadOnly,
                ["input/click"] = HeraRiskClass.Write,
                ["input/drag"] = HeraRiskClass.Write,
                ["input/keyboard"] = HeraRiskClass.Write,
                ["input/mouse"] = HeraRiskClass.Write,
                ["input/pointer_down"] = HeraRiskClass.Write,
                ["input/pointer_up"] = HeraRiskClass.Write,
                ["input/record"] = HeraRiskClass.Write,
                ["input/replay"] = HeraRiskClass.Write,
                ["input/scroll"] = HeraRiskClass.Write,
                ["input/sequence"] = HeraRiskClass.Write,
                ["input/submit"] = HeraRiskClass.Write,
                ["manage_animation/add_parameter"] = HeraRiskClass.Write,
                ["manage_animation/add_state"] = HeraRiskClass.Write,
                ["manage_animation/add_transition"] = HeraRiskClass.Write,
                ["manage_animation/create_clip"] = HeraRiskClass.Write,
                ["manage_animation/create_controller"] = HeraRiskClass.Write,
                ["manage_animation/set_curve"] = HeraRiskClass.Write,
                ["manage_asset_import/set"] = HeraRiskClass.Write,
                ["manage_assets/copy"] = HeraRiskClass.Write,
                ["manage_assets/create"] = HeraRiskClass.Write,
                ["manage_assets/mkdir"] = HeraRiskClass.Write,
                ["manage_components/add"] = HeraRiskClass.Write,
                ["manage_components/set"] = HeraRiskClass.Write,
                ["manage_editor/add_layer"] = HeraRiskClass.Write,
                ["manage_editor/add_tag"] = HeraRiskClass.Write,
                ["manage_editor/set_selection"] = HeraRiskClass.Write,
                ["manage_editor/pause"] = HeraRiskClass.Write,
                ["manage_editor/play"] = HeraRiskClass.Write,
                ["manage_editor/set_active_tool"] = HeraRiskClass.Write,
                ["manage_editor/stop"] = HeraRiskClass.Write,
                ["manage_gameobject/create"] = HeraRiskClass.Write,
                ["manage_gameobject/duplicate"] = HeraRiskClass.Write,
                ["manage_gameobject/move"] = HeraRiskClass.Write,
                ["manage_gameobject/set_active"] = HeraRiskClass.Write,
                ["manage_gameobject/set_name"] = HeraRiskClass.Write,
                ["manage_gameobject/set_parent"] = HeraRiskClass.Write,
                ["manage_material/create"] = HeraRiskClass.Write,
                ["manage_material/set"] = HeraRiskClass.Write,
                ["manage_material/set_shader"] = HeraRiskClass.Write,
                ["manage_prefab/add_component"] = HeraRiskClass.Write,
                ["manage_prefab/create"] = HeraRiskClass.Write,
                ["manage_prefab/instantiate"] = HeraRiskClass.Write,
                ["manage_ui/create"] = HeraRiskClass.Write,
                ["manage_ui/set_anchor"] = HeraRiskClass.Write,
                ["manage_ui/set_rect"] = HeraRiskClass.Write,
                ["profiler/disable"] = HeraRiskClass.Write,
                ["profiler/enable"] = HeraRiskClass.Write,
                ["scene/load"] = HeraRiskClass.Write,
                ["scene/save"] = HeraRiskClass.Write,
                ["manage_assets/delete"] = HeraRiskClass.Destructive,
                ["manage_assets/move"] = HeraRiskClass.Destructive,
                ["manage_components/remove"] = HeraRiskClass.Destructive,
                ["manage_editor/remove_layer"] = HeraRiskClass.Destructive,
                ["manage_editor/remove_tag"] = HeraRiskClass.Destructive,
                ["manage_gameobject/destroy"] = HeraRiskClass.Destructive,
                ["manage_prefab/remove_component"] = HeraRiskClass.Destructive,
                ["profiler/clear"] = HeraRiskClass.Destructive,
                ["scene/close"] = HeraRiskClass.Destructive,
                ["manage_packages/add"] = HeraRiskClass.PackageChange,
                ["manage_packages/embed"] = HeraRiskClass.PackageChange,
                ["manage_packages/remove"] = HeraRiskClass.PackageChange,
            };
    }
}
