// Code generated by tools/generate-runtime-contracts; DO NOT EDIT.

package protocol

const (
	RuntimeContractsSchemaVersion = "hera.runtime-contracts/1"
	ToolCatalogSchemaVersion      = "hera.tool-catalog/1"
	ExecutionProtocolVersion      = "hera.execution/1"

	FeatureApprovalV1          = "approval_v1"
	FeatureDomainEpochV1       = "domain_epoch_v1"
	FeatureExecutionProtocolV1 = "execution_protocol_v1"
	FeatureOperationLedgerV1   = "operation_ledger_v1"
	FeatureTaskBridgeV1        = "task_bridge_v1"
	FeatureToolCatalogV1       = "tool_catalog_v1"

	AssetConfigLockVersion                = 1
	AssetConfigLockStaleAfterMilliseconds = int64(120000)
)
